name: WakaTime Stats

on:
  schedule:
    - cron: "30 21 * * *" # ‚è∞ Runs at 23h30 CEST / 21h30 UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      uses: athul/waka-readme@v0.2.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
